; Generated by banks.js
.include "../banks-gen.inc"
.segment "RODATA"
ow0: .include "cain_and_abel.ow"
.segment "JUMPS"
.word ow0
.segment "RODATA"
ow1: .include "ff3a.ow"
.segment "JUMPS"
.word ow1
.segment "RODATA"
ow2: .include "ff3b.ow"
.segment "JUMPS"
.word ow2
.segment "RODATA"
ow3: .include "ff3c.ow"
.segment "JUMPS"
.word ow3
.segment "RODATA"
ow4: .include "ff3d.ow"
.segment "JUMPS"
.word ow4
