; Generated by banks.js
.include "../banks-gen.inc"
.segment "RODATA"
ow0: .include "cain_and_abel.ow"
.segment "JUMPS"
.word ow0
.segment "RODATA"
ow1: .include "civil_war_battlefield.ow"
.segment "JUMPS"
.word ow1
.segment "RODATA"
ow2: .include "cyrus_home.ow"
.segment "JUMPS"
.word ow2
.segment "RODATA"
ow3: .include "peewee.ow"
.segment "JUMPS"
.word ow3
.segment "RODATA"
ow4: .include "rutty_road.ow"
.segment "JUMPS"
.word ow4
.segment "RODATA"
ow5: .include "ames_home.ow"
.segment "JUMPS"
.word ow5
.segment "RODATA"
ow6: .include "ff3a.ow"
.segment "JUMPS"
.word ow6
.segment "RODATA"
ow7: .include "ff3b.ow"
.segment "JUMPS"
.word ow7
.segment "RODATA"
ow8: .include "ff3c.ow"
.segment "JUMPS"
.word ow8
.segment "RODATA"
ow9: .include "ff3d.ow"
.segment "JUMPS"
.word ow9
