; Generated by banks.js
.export _spriteTable
.export _characterTable
.segment "RODATA"
_spriteTable:
.import _abel
.word _abel
.import _cain
.word _cain
_characterTable:
.import _abelC
.word _abelC
.import _cainC
.word _cainC
