spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 0;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 15;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 1;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 14;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 2;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 13;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 3;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 13;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 4;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 12;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 5;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 11;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 6;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 10;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 7;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 9;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 8;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 9;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 9;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 8;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 10;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 7;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 11;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 7;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 12;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 6;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 13;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 5;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 14;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 5;
spriteLocs[pwIdx].xt = 9;
spriteLocs[pwIdx].xs = 15;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 4;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 0;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 4;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 1;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 3;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 2;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 3;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 3;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 2;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 4;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 2;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 5;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 6;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 7;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 8;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 9;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 10;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 11;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 12;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 13;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 14;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 10;
spriteLocs[pwIdx].xs = 15;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 0;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 1;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 7;
spriteLocs[pwIdx].ys = 16;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 2;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 3;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 4;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 5;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 1;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 6;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 2;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 7;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 2;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 8;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 3;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 9;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 3;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 10;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 4;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 11;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 4;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 12;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 5;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 13;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 5;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 14;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 6;
spriteLocs[pwIdx].xt = 11;
spriteLocs[pwIdx].xs = 15;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 7;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 0;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 7;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 1;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 8;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 2;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 9;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 3;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 9;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 4;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 10;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 5;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 11;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 6;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 12;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 7;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 13;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 8;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 13;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 9;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 14;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 10;
updateSprite(pwIdx);
pause(1);
spriteLocs[pwIdx].yt = 8;
spriteLocs[pwIdx].ys = 15;
spriteLocs[pwIdx].xt = 12;
spriteLocs[pwIdx].xs = 11;
updateSprite(pwIdx);
pause(1);
